# permissions for end users to view guestbook1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guestbook1-viewer-role
rules:
- apiGroups:
  - webapp.mycrd.com
  resources:
  - guestbook1s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.mycrd.com
  resources:
  - guestbook1s/status
  verbs:
  - get
